all: 1-1-quickfind-solution \
	1-2-quickunion-solution \
	1-3-quickunion-weighted \
	1-4-quickunion-path-compression-halving

1-1-quickfind-solution: # use default rule

1-2-quickunion-solution: # use default rule

1-3-quickunion-weighted: # use default rule

1-4-quickunion-path-compression-halving: # use default rule
